### ISSUE TITLE
The plugin searches for this temporary path Library\PackageCache

### ISSUE THREAD

**Issue by SyaoranChang** [treething77/coroutinery#1]
Hi,

The plugin searches for the temporary path Library\PackageCache
The full path is
"D:\\Work\\Project0035\\GameClientP35_Git\\Library\\PackageCache\\com.gameanalytics.sdk@7.9.1\\Runtime\\Scripts\\Events\\GA_SpecialEvents.cs"
It seems that the lack of an “Assets” path is the cause.

This is a GameAnalytics plugin.
https://docs.gameanalytics.com/integrations/sdk/unity
I created a new project and installed only the com.gameanalytics.sdk plugin without error, sorry I can't create a reproducible project.

The error log:
> [Exception] ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
String.Substring() at <afe256a0391e468fbcdb82154daad696>:0
String.Substring() at <afe256a0391e468fbcdb82154daad696>:0
ScriptCompilationHook.BuildAssemblySourceMapping() at /coroutinery/Editor/ScriptCompilationHook.cs:169
ScriptCompilationHook.RebuildAll() at /coroutinery/Editor/ScriptCompilationHook.cs:39

**Comment by treething77** [comment]
I reproduced the issue with the GA package and pushed a fix. Hope that fixes it for you!
